/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes,extraRequire}
 * tslint:disable
 */

var styles = ['']
export { styles }
//# sourceMappingURL=todo.component.scss.shim.ngstyle.js.map
